[build-system]
requires = ["setuptools>=64", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "posym"
description = "posym module"
dynamic = ["version"]
readme = { file = "README.md", content-type = "text/markdown" }
license = {file = "LICENSE"}
requires-python = ">=3.8"
keywords = ["symmetry", "molecular symmetry", "group theory"]
authors = [
    { name = "Abel Carreras", email = "abelcarreras83@gmail.com" }
]
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "PyYaml",
]

[project.urls]
"Source" = "https://github.com/abelcarreras/posym"

[project.optional-dependencies]
docs = [
    "sphinx>=7",
    "sphinx-rtd-theme",
    "sphinx-copybutton",
    "nbsphinx",
    "nbconvert<7.17",
]

[tool.setuptools]
packages = ["posym", "posym.operations", "posym.permutation"]


[tool.setuptools.dynamic]
version = { attr = "posym.__version__" }
