[build-system]
requires = ["setuptools", "wheel", "numpy", "versioningit"]
build-backend = "setuptools.build_meta"

[project]
name = "posym"
description = "posym module"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
keywords = ["symmetry", "molecular symmetry", "group theory"]
authors = [
    { name = "Abel Carreras", email = "abelcarreras83@gmail.com" }
]
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "PyYaml",
]

[project.urls]
"Source" = "https://github.com/abelcarreras/posym"

[tool.setuptools]
packages = ["posym", "posym.operations", "posym.permutation"]


[tool.versioningit]
default-version = "1+unknown"

[tool.versioningit.format]
distance = "{base_version}+{distance}.{vcs}{rev}"
dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"

[tool.versioningit.vcs]
# The method key:
method = "git"  # <- The method name
# Parameters to pass to the method:
match = ["*"]
default-tag = "1.0.0"

[tool.versioningit.write]
file = "posym/_version.py"